#!/usr/bin/env python3
"""Generate flash-only GPS timezone data; no firmware build or extra packages.

python3 scripts/generate_timezones.py --lookup /tmp/awok-tz-lookup.tgz \
    --tzdata /tmp/awok-tzdata.whl

Download the pinned archives listed below first. Never uses host timezone data.
"""
import argparse
import hashlib
import io
import json
from pathlib import Path
import re
import tarfile
import zipfile
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

LOOKUP_URL = 'https://registry.npmjs.org/@photostructure/tz-lookup/-/tz-lookup-11.7.0.tgz'
LOOKUP_SHA = 'a6b0b3e9196be577694deca9424617421a967ff4de6405c5d61508a29293052b'
TZDATA_URL = 'https://files.pythonhosted.org/packages/f9/bc/8737e8d54cf51106118039b83f485a4783112fab49ea9d044b234978a46e/tzdata-2026.4-py2.py3-none-any.whl'
TZDATA_SHA = 'c2169a8b0a7a5e9674da5a135ccdfb2b3e671b333ed9fed17b41f73c34476e81'
ROOT = Path(__file__).resolve().parents[1]
START = 1577836800  # 2020-01-01 UTC
END = 4102444800    # 2100-01-01 UTC (exclusive)


def checked(path, sha):
    data = Path(path).read_bytes()
    if hashlib.sha256(data).hexdigest() != sha:
        raise ValueError(f'{path}: SHA-256 mismatch')
    return data


def state(zone, epoch):
    local = datetime.fromtimestamp(epoch, timezone.utc).astimezone(zone)
    offset = int(local.utcoffset().total_seconds())
    assert offset % 60 == 0
    return (offset // 60) * 2 + bool(local.dst())


def periods(zone):
    current = state(zone, START)
    result = [(0, current)]
    # tzdb has no two post-2020 transitions less than one day apart. Probe daily
    # and bisect to the exact UTC second; ZoneInfo expands the TZif future rules.
    for probe in range(START + 86400, END + 1, 86400):
        value = state(zone, probe)
        if value == current:
            continue
        low, high = probe - 86400, probe
        while high - low > 1:
            middle = (low + high) // 2
            if state(zone, middle) == current:
                low = middle
            else:
                high = middle
        if high < END:
            result.append((high - START, value))
        current = value
    return tuple(result)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--lookup', required=True)
    parser.add_argument('--tzdata', required=True)
    args = parser.parse_args()
    with tarfile.open(fileobj=io.BytesIO(checked(args.lookup, LOOKUP_SHA))) as archive:
        source = archive.extractfile('package/tz.js').read().decode()
        license_text = archive.extractfile('package/LICENSE').read()
    # Parse literals only, never evaluate downloaded JavaScript.
    match = re.search(r'var X=("(?:[^"\\]|\\.)*"),T=(\[.*?\]);', source)
    if not match:
        raise ValueError('Upstream lookup encoding changed; review generator')
    tree, names = map(json.loads, match.groups())
    all_periods, schedules, zones = [], {}, []
    with zipfile.ZipFile(io.BytesIO(checked(args.tzdata, TZDATA_SHA))) as archive:
        for name in names:
            zone = ZoneInfo.from_file(io.BytesIO(archive.read('tzdata/zoneinfo/' + name)), key=name)
            schedule = periods(zone)
            if schedule not in schedules:
                schedules[schedule] = len(all_periods)
                all_periods.extend(schedule)
            zones.append((name, schedules[schedule], len(schedule)))
        notice = archive.read('tzdata-2026.4.dist-info/licenses/LICENSE')
        apache = archive.read('tzdata-2026.4.dist-info/licenses/licenses/LICENSE_APACHE')
    lines = ['// Generated by scripts/generate_timezones.py; do not hand edit.',
             '// Map: @photostructure/tz-lookup 11.7.0 (CC0); rules: IANA 2026d.',
             '// See third_party/timezones/README.md for sources, limits and licenses.',
             '#pragma once', '#include <stdint.h>', 'namespace AwokTime {',
             f'constexpr int64_t kEpoch = {START}LL, kEnd = {END}LL;',
             'struct Zone { const char* name; uint16_t first, count; };',
             'struct Period { uint32_t since; int16_t offsetAndDst; };',
             'static const char kTree[] =']
    lines += ['  ' + json.dumps(tree[i:i+100]) for i in range(0, len(tree), 100)]
    lines += [';', 'static const Zone kZones[] = {']
    lines += [f'  {{{json.dumps(name)}, {first}, {count}}},' for name, first, count in zones]
    lines += ['};', 'static const Period kPeriods[] = {']
    lines += [f'  {{{since}U, {code}}},' for since, code in all_periods]
    lines += ['};', '}  // namespace AwokTime', '']
    assert len(all_periods) < 65536
    (ROOT / 'AWOKxDAG/timezone_data.h').write_text('\n'.join(lines))
    out = ROOT / 'third_party/timezones'
    out.mkdir(parents=True, exist_ok=True)
    (out / 'tz-lookup-LICENSE.txt').write_bytes(license_text)
    (out / 'tzdata-LICENSE.txt').write_bytes(notice)
    (out / 'tzdata-APACHE.txt').write_bytes(apache)
    print(f'{len(tree)} map bytes, {len(zones)} zones, {len(schedules)} unique schedules, '
          f'{len(all_periods)} periods (~{len(tree)+len(all_periods)*8+len(zones)*8+sum(len(n)+1 for n in names):,} flash bytes)')


if __name__ == '__main__':
    main()
